name: weather_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  either_dart: ^0.1.3
  flutter_spinkit: ^5.1.0
  geolocator: ^7.7.1 
  flutter_svg: ^0.23.0+1
  intl: ^0.17.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/main_icons/clear_sky_day.svg
    - assets/images/main_icons/clear_sky_night.svg
    - assets/images/main_icons/few_clouds_night.svg
    - assets/images/main_icons/few_clouds.svg
    - assets/images/main_icons/mist.svg
    - assets/images/main_icons/rain.svg
    - assets/images/main_icons/scattered_clouds.svg
    - assets/images/main_icons/shower_rain.svg
    - assets/images/main_icons/snow.svg
    - assets/images/main_icons/thunderstorm.svg
    - assets/images/small_icons/clear_sky_day.svg
    - assets/images/small_icons/clear_sky_night.svg
    - assets/images/small_icons/few_clouds_night.svg
    - assets/images/small_icons/few_clouds.svg
    - assets/images/small_icons/mist.svg
    - assets/images/small_icons/rain.svg
    - assets/images/small_icons/scattered_clouds.svg
    - assets/images/small_icons/shower_rain.svg
    - assets/images/small_icons/snow.svg
    - assets/images/small_icons/thunderstorm.svg
    - assets/images/additional_icons/max_temp.svg
    - assets/images/additional_icons/min_temp.svg


fonts:
  - family: Montserrat
    fonts:
      - asset: assets/fonts/Montserrat-Medium.ttf
        weight: 500
      - asset: assets/fonts/Montserrat-Bold.ttf
        weight: 700  